version: '3.8'

services:
  postgres:
    container_name: projeto-java-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: projeto-java
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres