/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JTextField;
import controller.CriarClienteController;

/**
 *
 * @author leandroalencar
 */
public class CriarCliente extends javax.swing.JFrame {
    private CriarClienteController controller;

    /**
     * Creates new form CriarCliente
     */
    public CriarCliente() {
        initComponents();
        controller = new CriarClienteController(this);
    }
    
    public int getTipoContaSelecionada() {
    if (buttonContaCorrente.isSelected()) {
        return 1;
    } else if (buttonContaSalario.isSelected()) {
        return 2;
    } else if (buttonContaPoupanca.isSelected()) {
        return 3;
    } 
    return 0;
}

    public JButton getButtonCriarCliente() {
        return buttonCriarCliente;
    }

    public void setButtonCriarCliente(JButton buttonCriarCliente) {
        this.buttonCriarCliente = buttonCriarCliente;
    }

    public JTextField getEntradaCPF() {
        return entradaCPF;
    }

    public void setEntradaCPF(JTextField entradaCPF) {
        this.entradaCPF = entradaCPF;
    }

    public JTextField getEntradaNome() {
        return entradaNome;
    }

    public void setEntradaNome(JTextField entradaNome) {
        this.entradaNome = entradaNome;
    }

    public JTextField getEntradaSaldo() {
        return entradaSaldo;
    }

    public void setEntradaSaldo(JTextField entradaSaldo) {
        this.entradaSaldo = entradaSaldo;
    }

    public JTextField getEntradaSenha() {
        return entradaSenha;
    }

    public void setEntradaSenha(JTextField entradaSenha) {
        this.entradaSenha = entradaSenha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaNome = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        entradaSenha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entradaCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        entradaSaldo = new javax.swing.JTextField();
        buttonCriarCliente = new javax.swing.JButton();
        buttonContaSalario = new javax.swing.JRadioButton();
        buttonContaCorrente = new javax.swing.JRadioButton();
        buttonContaPoupanca = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRIE UM NOVO CLIENTE");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite o nome");

        labelSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSenha.setText("Digite a senha");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Digite o CPF");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Digite o saldo inicial");

        buttonCriarCliente.setText("Criar");
        buttonCriarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCriarClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonContaSalario);
        buttonContaSalario.setText("Conta Salário");
        buttonContaSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContaSalarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonContaCorrente);
        buttonContaCorrente.setText("Conta Corrente");

        buttonGroup1.add(buttonContaPoupanca);
        buttonContaPoupanca.setText("Conta Poupança");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCriarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(entradaSaldo)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entradaNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entradaSenha)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entradaCPF)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(buttonContaSalario)
                .addGap(29, 29, 29)
                .addComponent(buttonContaCorrente)
                .addGap(41, 41, 41)
                .addComponent(buttonContaPoupanca)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entradaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonContaSalario)
                    .addComponent(buttonContaCorrente)
                    .addComponent(buttonContaPoupanca))
                .addGap(40, 40, 40)
                .addComponent(buttonCriarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonContaSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContaSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonContaSalarioActionPerformed

    private void buttonCriarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCriarClienteActionPerformed
       controller.CriarCliente();
    }//GEN-LAST:event_buttonCriarClienteActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttonContaCorrente;
    private javax.swing.JRadioButton buttonContaPoupanca;
    private javax.swing.JRadioButton buttonContaSalario;
    private javax.swing.JButton buttonCriarCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField entradaCPF;
    private javax.swing.JTextField entradaNome;
    private javax.swing.JTextField entradaSaldo;
    private javax.swing.JTextField entradaSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelSenha;
    // End of variables declaration//GEN-END:variables
}
