/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DebitarClienteController;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author leandroalencar
 */
public class DebitarCliente extends javax.swing.JFrame {
    private DebitarClienteController controller;

    /**
     * Creates new form DebitarCliente1
     */
    public DebitarCliente() {
        initComponents();
        controller = new DebitarClienteController(this);
    }
    
    /**
     *
     * @return
     */
    public int getTipoContaSelecionada() {
        if (buttonContaCorrente.isSelected()) {
            return 1;
        } else if (buttonContaSalario.isSelected()) {
            return 2;
        } else if (buttonContaPoupanca.isSelected()) {
            return 3;
        }
        return 0;
    }

    /**
     *
     * @return
     */
    public JRadioButton getButtonContaCorrente() {
        return buttonContaCorrente;
    }

    /**
     *
     * @return
     */
    public JRadioButton getButtonContaPoupanca() {
        return buttonContaPoupanca;
    }

    /**
     *
     * @return
     */
    public JRadioButton getButtonContaSalario() {
        return buttonContaSalario;
    }

    /**
     *
     * @return
     */
    public JButton getButtonDebitar() {
        return buttonDebitar;
    }

    /**
     *
     * @return
     */
    public JTextField getEntradaCPF() {
        return entradaCPF;
    }

    /**
     *
     * @return
     */
    public JTextField getEntradaSenha() {
        return entradaSenha;
    }

    /**
     *
     * @return
     */
    public JTextField getEntradaValor() {
        return entradaValor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        entradaCPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        entradaSenha = new javax.swing.JTextField();
        entradaValor = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        labelConta = new javax.swing.JLabel();
        buttonContaCorrente = new javax.swing.JRadioButton();
        buttonContaSalario = new javax.swing.JRadioButton();
        buttonContaPoupanca = new javax.swing.JRadioButton();
        buttonDebitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Debitar Cliente");

        labelCPF.setText("Digite o CPF");

        entradaCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Digite a Senha");

        labelValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelValor.setText("Digite o valor");

        labelConta.setText("Tipo de Conta");

        buttonGroup1.add(buttonContaCorrente);
        buttonContaCorrente.setText("Conta Corrente");

        buttonGroup1.add(buttonContaSalario);
        buttonContaSalario.setText("Conta Salário");

        buttonGroup1.add(buttonContaPoupanca);
        buttonContaPoupanca.setText("Conta Poupança");

        buttonDebitar.setText("Debitar");
        buttonDebitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDebitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaValor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entradaSenha)
                            .addComponent(entradaCPF)
                            .addComponent(labelValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelCPF)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(142, 142, 142))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelConta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(buttonContaCorrente)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDebitar)
                            .addComponent(buttonContaSalario))))
                .addGap(31, 31, 31)
                .addComponent(buttonContaPoupanca))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entradaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entradaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelValor)
                .addGap(14, 14, 14)
                .addComponent(entradaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labelConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonContaCorrente)
                    .addComponent(buttonContaSalario)
                    .addComponent(buttonContaPoupanca))
                .addGap(18, 18, 18)
                .addComponent(buttonDebitar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDebitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDebitarActionPerformed
        controller.debitarValor();
    }//GEN-LAST:event_buttonDebitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebitarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebitarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebitarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebitarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DebitarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttonContaCorrente;
    private javax.swing.JRadioButton buttonContaPoupanca;
    private javax.swing.JRadioButton buttonContaSalario;
    private javax.swing.JButton buttonDebitar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField entradaCPF;
    private javax.swing.JTextField entradaSenha;
    private javax.swing.JTextField entradaValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValor;
    // End of variables declaration//GEN-END:variables
}
