/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import controller.DepositarClienteController;

/**
 *
 * @author x
 */
public class Deposito extends javax.swing.JFrame {
    private DepositarClienteController controller;

    /**
     * Creates new form Deposito
     */
    public Deposito() {
        initComponents();
        controller = new DepositarClienteController(this);
    }
    
    public int getTipoContaSelecionada() {
        if (buttonContaCorrente.isSelected()) {
            return 1;
        } else if (buttonContaSalario.isSelected()) {
            return 2;
        } else if (buttonContaPoupanca.isSelected()) {
            return 3;
        }
        return 0;
    }

    public JRadioButton getButtonContaCorrente() {
        return buttonContaCorrente;
    }

    public JRadioButton getButtonContaPoupanca() {
        return buttonContaPoupanca;
    }

    public JRadioButton getButtonContaSalario() {
        return buttonContaSalario;
    }

    public JButton getButtonDepositar() {
        return buttonDepositar;
    }

    public JTextField getEntradaCPF() {
        return entradaCPF;
    }

    public JTextField getEntradaSenha() {
        return entradaSenha;
    }

    public JTextField getEntradaValor() {
        return entradaValor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entradaCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        entradaSenha = new javax.swing.JTextField();
        buttonDepositar = new javax.swing.JButton();
        labelConta = new javax.swing.JLabel();
        buttonContaCorrente = new javax.swing.JRadioButton();
        buttonContaSalario = new javax.swing.JRadioButton();
        buttonContaPoupanca = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Depositar na Conta Selecionada");

        jLabel2.setText("Digite o Valor:");

        entradaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaValorActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite o CPF:");

        entradaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCPFActionPerformed(evt);
            }
        });

        jLabel4.setText("Digite a senha:");

        entradaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaSenhaActionPerformed(evt);
            }
        });

        buttonDepositar.setText("Depositar");
        buttonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDepositarActionPerformed(evt);
            }
        });

        labelConta.setText("Tipo de Conta");

        buttonGroup1.add(buttonContaCorrente);
        buttonContaCorrente.setText("Conta Corrente");

        buttonGroup1.add(buttonContaSalario);
        buttonContaSalario.setText("Conta Salário");

        buttonGroup1.add(buttonContaPoupanca);
        buttonContaPoupanca.setText("Conta Poupança");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(entradaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(entradaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonContaCorrente)
                        .addGap(155, 155, 155)
                        .addComponent(buttonContaPoupanca))
                    .addComponent(labelConta)
                    .addComponent(buttonDepositar)
                    .addComponent(entradaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonContaSalario))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entradaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entradaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonContaCorrente)
                    .addComponent(buttonContaSalario)
                    .addComponent(buttonContaPoupanca))
                .addGap(18, 18, 18)
                .addComponent(buttonDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaValorActionPerformed

    private void entradaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaCPFActionPerformed

    private void entradaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaSenhaActionPerformed

    private void buttonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDepositarActionPerformed
        controller.DepositarValor();
    }//GEN-LAST:event_buttonDepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttonContaCorrente;
    private javax.swing.JRadioButton buttonContaPoupanca;
    private javax.swing.JRadioButton buttonContaSalario;
    private javax.swing.JButton buttonDepositar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField entradaCPF;
    private javax.swing.JTextField entradaSenha;
    private javax.swing.JTextField entradaValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelConta;
    // End of variables declaration//GEN-END:variables
}
