/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author x
 */
public class MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form MenuCliente
     */
    public MenuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonDebitarCliente = new javax.swing.JButton();
        buttonDepositar = new javax.swing.JButton();
        buttonExibirSaldoCliente = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Painel Cliente");

        buttonDebitarCliente.setText("Debitar da conta selecionada");
        buttonDebitarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDebitarClienteActionPerformed(evt);
            }
        });

        buttonDepositar.setText("Depositar na conta selecionada");
        buttonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDepositarActionPerformed(evt);
            }
        });

        buttonExibirSaldoCliente.setText("Exibir saldo das contas do Cliente");
        buttonExibirSaldoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExibirSaldoClienteActionPerformed(evt);
            }
        });

        jButton4.setText("Exibir extrato da conta corrente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonExibirSaldoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                .addComponent(buttonDebitarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(buttonDebitarCliente)
                .addGap(18, 18, 18)
                .addComponent(buttonDepositar)
                .addGap(16, 16, 16)
                .addComponent(buttonExibirSaldoCliente)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDebitarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDebitarClienteActionPerformed

        DebitarCliente debitarCliente = new DebitarCliente();
        debitarCliente.setVisible(true);
    }//GEN-LAST:event_buttonDebitarClienteActionPerformed

    private void buttonExibirSaldoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExibirSaldoClienteActionPerformed
        SaldoCliente saldoCliente = new SaldoCliente();
        saldoCliente.setVisible(true);
    }//GEN-LAST:event_buttonExibirSaldoClienteActionPerformed

    private void buttonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDepositarActionPerformed
        Deposito depositarCliente = new Deposito();
        depositarCliente.setVisible(true);
                
    }//GEN-LAST:event_buttonDepositarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDebitarCliente;
    private javax.swing.JButton buttonDepositar;
    private javax.swing.JButton buttonExibirSaldoCliente;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
